batch_run: true
sanity_check: true # will run the script but stop short of API call
specific_solvers:
#  - 'claude_llm'
#  - 'gemini_pro_llm'
query_constraints: []
query_excludes: []
experiment_name: sample-queries
all_ingredients_file: logs_extraction/20251008-1807-generation_output.jsonl # !! Use the provided file as a test run with sanity_check=true.
log_dir: logs_unification
unifier_models: # Assumes Claude use
  - claude-opus-4-20250514
