batch_run: true
sanity_check: true
specific_solvers:
#  - 'claude_llm'
#  - 'gemini_pro_llm'
query_constraints: []
query_excludes: []
experiment_name: sample-queries
solver_reports_path: ../meta_evaluation/system_reports/test/
log_dir: logs_extraction
extractor_model: claude-opus-4-20250514 # Assumes Claude Use